"""HireHi public resume hooks, kept independent from vacancy locators."""

NAME = ".resume-public-name"
TITLE = ".resume-public-position, .resume-public-title"
GRADE = ".resume-public-grade, .resume-grade"
CITY = ".resume-public-location, .resume-location"
WORK_FORMAT = ".resume-public-work-format, .resume-work-format"
EMPLOYMENT = ".resume-public-employment-type, .resume-employment-type"
ABOUT = ".resume-public-about, .resume-about"
PHONE = ".resume-public-phone, .resume-phone"
EMAIL = ".resume-public-email-link, .resume-public-email, .resume-email"
MESSENGER = ".resume-public-contact-link, .resume-public-messenger, .resume-messenger"
LINK = ".resume-public-contact-link, .resume-portfolio a[href]"
SPECIALIZATION = ".resume-public-specialization, .resume-specialization"
RELOCATION = ".resume-public-relocation, .resume-relocation"
TRIPS = ".resume-public-business-trips, .resume-business-trips"
EXPERIENCE = ".resume-public-list-item"
EXPERIENCE_COMPANY = ".resume-public-list-company"
EXPERIENCE_TITLE = ".resume-public-list-title"
EXPERIENCE_PERIOD = ".resume-public-list-dates"
EXPERIENCE_DESCRIPTION = ".resume-public-list-description"
PROJECT = ".resume-public-projects .resume-public-list-item"
SKILL = ".resume-public-skill-chip"
EDUCATION = ".resume-public-education .resume-public-list-item"
LANGUAGE = ".resume-public-language-line"
COURSE = ".resume-public-courses .resume-public-list-item"
CERTIFICATION = ".resume-public-certifications .resume-public-list-item"
AWARD = ".resume-public-awards .resume-public-list-item"
PORTFOLIO = ".resume-public-portfolio .resume-public-list-item"
ADDITIONAL = ".resume-public-achievements-item, .resume-additional-section, .resume-additional .list-item"
UPDATED = "time[datetime], .resume-updated-at"
ACCOUNT_RESUME_LINKS = "a[href*='/resume/']"
