"""HireHi public resume hooks, kept independent from vacancy locators."""

NAME = ".resume-public-name"
TITLE = ".resume-public-position, .resume-public-title"
HEADER = "section.resume-public-header-card, .resume-public-header"
HEADER_META = ".resume-public-header .resume-public-meta, .resume-public-header-meta"
HEADER_GRADE = ".resume-public-header .resume-public-grade, .resume-public-header [data-field='grade']"
HEADER_WORK_FORMAT = ".resume-public-header .resume-public-work-format, .resume-public-header [data-field='work-format']"
HEADER_EMPLOYMENT = ".resume-public-header .resume-public-employment-type, .resume-public-header [data-field='employment-type']"
GRADE = HEADER_GRADE
CITY = ".resume-public-header .resume-public-location, .resume-location"
WORK_FORMAT = HEADER_WORK_FORMAT
EMPLOYMENT = HEADER_EMPLOYMENT
ABOUT = ".resume-public-about, .resume-about"
PHONE = ".resume-public-phone, .resume-phone"
EMAIL = ".resume-public-email-link, .resume-public-email, .resume-email"
MESSENGER = ".resume-public-contact-link, .resume-public-messenger, .resume-messenger"
LINK = ".resume-public-contact-link, .resume-portfolio a[href]"
SPECIALIZATION = ".resume-public-specialization, .resume-specialization"
RELOCATION = ".resume-public-relocation, .resume-relocation"
TRIPS = ".resume-public-business-trips, .resume-business-trips"
EXPERIENCE = ".resume-public-list-item"
EXPERIENCE_COMPANY = ".resume-public-list-company"
EXPERIENCE_TITLE = ".resume-public-list-subtitle, .resume-public-position, .resume-public-list-title"
EXPERIENCE_PERIOD = ".resume-public-list-dates"
EXPERIENCE_DATE_LINE = ".resume-public-date-line, [data-field='date']"
EXPERIENCE_DESCRIPTION = ".resume-public-list-description p, .resume-public-duties, [data-field='duties']"
EXPERIENCE_DESCRIPTION_CONTAINER = ".resume-public-list-description"
EXPERIENCE_ACHIEVEMENT = ".resume-public-achievements-item, .resume-public-achievement, [data-field='achievement']"
EXPERIENCE_LOCATION = ".resume-public-location-meta, .resume-public-location-inline, [data-field='location']"
EXPERIENCE_COMPANY_LINK = ".resume-public-list-company a, a[data-field='company-url']"
EXPERIENCE_WORK_FORMAT = ".resume-public-work-format, [data-field='work-format']"
EXPERIENCE_EMPLOYMENT = ".resume-public-employment-type, [data-field='employment-type']"
EXPERIENCE_GRADE = ".resume-public-grade, [data-field='grade']"
EXPERIENCE_INDUSTRIES = ".resume-public-industry, .resume-public-industries, [data-field='industry'], [data-field='industries']"
EXPERIENCE_DURATION = ".resume-public-duration, [data-field='duration']"
SECTIONS = "section.resume-public-card, section[data-section], [data-resume-section], .resume-public-section"
ITEMS = ".resume-public-list-item, [data-resume-item]"
SECTION_TITLE = ".resume-public-section-title, [data-section-title], h2, h3"
SKILL_ROW = ".resume-public-skills-row, [data-skill-category]"
SKILL_LABEL = ".resume-public-skills-label, [data-skill-category]"
SKILL = ".resume-public-skill-chip, [data-skill]"
SKILL_SECTION = ".resume-public-skills-layout, [data-section='skills']"
LANGUAGE = ".resume-public-language-line, [data-language]"
LANGUAGE_NAME = ".resume-public-language-name, [data-field='language']"
# The level container already includes the description text.  Exclude nested
# description/proficiency nodes so a container and its child are not returned
# as two levels; standalone variants remain supported.
LANGUAGE_LEVEL = (
    ".resume-public-language-level, "
    ".resume-public-language-desc:not(.resume-public-language-level .resume-public-language-desc), "
    "[data-field='proficiency']:not(.resume-public-language-level [data-field='proficiency'])"
)
LANGUAGE_CODE = ".resume-public-language-code"
EDUCATION_SECTION = "[data-section='education'], .resume-public-education"
EDUCATION = ".resume-public-list-item"
EDUCATION_FACULTY = ".resume-public-faculty, [data-field='faculty']"
COURSE_SECTION = "[data-section='courses'], .resume-public-courses"
COURSE = ".resume-public-list-item"
AWARD_SECTION = "[data-section='awards'], .resume-public-awards"
AWARD = ".resume-public-list-item"
CERTIFICATION_SECTION = "[data-section='certifications'], .resume-public-certifications"
CERTIFICATION = ".resume-public-list-item"
ADDITIONAL_SECTION = "[data-section='additional'], .resume-public-additional, .resume-additional-section"
PROJECT = ".resume-public-projects .resume-public-list-item"
PORTFOLIO = ".resume-public-portfolio .resume-public-list-item"
ADDITIONAL = ".resume-public-achievements-item, .resume-additional-section, .resume-additional .list-item"
UPDATED = "time[datetime], .resume-updated-at"
ACCOUNT_RESUME_LINKS = "a[href*='/resume/']"
PHOTO = ".resume-public-photo img, .resume-public-photo source, [data-field='photo']"
PREFERRED_CONTACT = ".resume-public-preferred-contact, [data-field='preferred-contact']"
COMMUTE_TIME = ".resume-public-commute-time, [data-field='commute-time']"
