SEARCH_INPUT_NAME = "text"
VACANCY_LINK = "a[data-qa='serp-item__title']"
VACANCY_TITLE = "[data-qa='vacancy-title']"
COMPANY = "[data-qa='vacancy-company'], [data-qa='vacancy-company__details']"
DESCRIPTION = "[data-qa='vacancy-description']"
PAYMENT_FREQUENCY = "[data-qa='compensation-frequency-text']"
WORK_EXPERIENCE = "[data-qa='work-experience-text']"
EMPLOYMENT = "[data-qa='common-employment-text']"
HIRING_FORMAT = "[data-qa='vacancy-hiring-formats']"
WORK_SCHEDULE = "[data-qa='work-schedule-by-days-text']"
WORKING_HOURS = "[data-qa='working-hours-text']"
WORK_FORMAT = "[data-qa='work-formats-text']"
RESPONSE_BUTTON = "[data-qa='vacancy-response-link-top'], [data-qa='vacancy-response-link-bottom']"
RESPONSE_SUBMIT = "[data-qa='vacancy-response-submit-popup']"
COVER_LETTER_TOGGLE = "[data-qa='vacancy-response-letter-toggle']"
COVER_LETTER_INPUT = "[data-qa='vacancy-response-popup-form-letter-input']"
APPLICATION_QUESTION = "[data-qa^='vacancy-response-popup-form'] label"
APPLICATION_CONTROL = "textarea, select, input"
TASK_QUESTION = "[data-qa='task-question']"
ALREADY_APPLIED = "[data-qa='vacancy-response-link-view-topic']"
SUBMISSION_CONFIRMED = "[data-qa='vacancy-response-success'], [data-qa='vacancy-response-popup-success']"
SUBMISSION_TEXT_MARKERS = ("вы откликнулись", "отклик отправлен", "отклик успешно отправлен", "ваш отклик отправлен")
CAPTCHA_MARKERS = ("captcha", "Подтвердите, что вы не робот", "проверку безопасности")

# Explicit empty-result UI; a blank/error page is never exhaustion.
SEARCH_EMPTY = "[data-qa='vacancy-serp__vacancy-not-found'], [data-qa='vacancy-serp__no-results']"
