"""Zarplata print-resume DOM hooks, kept independent from HH."""

PRINT_MARKER = "body.bloko-print [data-qa='resume-print-action']"
NAME = "[data-qa='resume-personal-name']"
GENDER = "[data-qa='resume-personal-gender']"
AGE = "[data-qa='resume-personal-age']"
BIRTH_DATE = "[data-qa='resume-personal-birthday']"
PHOTO = "[data-qa='resume-photo']"
PHOTO_URL = "[data-qa='resume-photo'] img, [data-qa='resume-photo']"
PHONE = "[data-qa='resume-contact-phone'], [data-qa='resume-contact-preferred'] [data-qa='resume-contact-phone']"
EMAIL = "[data-qa='resume-contact-email']"
PREFERRED_CONTACT = "[data-qa='resume-contact-preferred-text'], [data-qa='resume-contact-preferred']"
CONTACT_COMMENT = "[data-qa='resume-block-contacts'] [data-qa='resume-view__text-with-overflow-tooltip']"
MESSENGER_LINK = "[data-qa^='resume-communication-method-'][data-qa$='-text'], [data-qa^='resume-communication-method-']"
MESSENGER = "[data-qa^='resume-communication-method-']:not([data-qa$='-text']), [data-qa='resume-phone-deep-link-viber']"
LINK = "[data-qa='resume-block-contacts'] a[href^='http']:not([data-qa^='resume-communication-method-'])"
TITLE = "[data-qa='resume-position']"
SPECIALIZATION = "[data-qa='resume-specialization-professional-role-value']"
GRADE = "[data-qa='resume-grade']"
SALARY = "[data-qa='resume-salary']"
EMPLOYMENT = "[data-qa='resume-specialization-employment-value']"
WORK_FORMAT = "[data-qa='resume-specialization-work-type-value']"
CITY = "[data-qa='resume-personal-address']"
RELOCATION = "[data-qa='relocation_relocation_possible']"
TRIPS = "[data-qa='resume-additional-info-business-trips-readiness']"
CITIZENSHIP = "[data-qa='resume-additional-info-citizenship']"
WORK_PERMIT = "[data-qa='resume-additional-info-work-ticket']"
COMMUTE_TIME = "[data-qa='resume-additional-info-travel-time']"
SELF_EMPLOYMENT = "[data-qa='resume-additional-info-self-employment']"
ABOUT = "[data-qa='resume-about-content']"
EXPERIENCE_BLOCK = "[data-qa='resume-experience-block']"
EXPERIENCE_TOTAL = "[data-qa='resume-experience-block-title']"
EXPERIENCE_ITEM = "[data-qa='resume-experience-block'] [data-qa='resume-experience-item']"
EXPERIENCE_PERIOD = "[data-qa='resume-experience-period']"
EXPERIENCE_FROM = "[data-qa='resume-experience-period-from']"
EXPERIENCE_TO = "[data-qa='resume-experience-period-to']"
EXPERIENCE_DURATION = "[data-qa='resume-experience-value']"
EXPERIENCE_COMPANY = "[data-qa='resume-experience-company-title']"
EXPERIENCE_AREA = "[data-qa='resume-experience-company-area']"
EXPERIENCE_COMPANY_URL = "[data-qa='resume-experience-company-url']"
EXPERIENCE_INDUSTRY = "[data-qa='resume-experience-industry-title'], [data-qa='resume-experience-subindustry-title']"
EXPERIENCE_TITLE = "[data-qa='resume-block-experience-position']"
EXPERIENCE_DESCRIPTION = "[data-qa='resume-block-experience-description']"
EXPERIENCE_ACHIEVEMENT = "[data-qa='resume-response-tag-achievements'], [data-qa='response-tag-achievements']"
PROJECT = "[data-qa='resume-project-item']"
PROJECT_NAME = "[data-qa='resume-project-name'], [data-qa='resume-project-title']"
SKILL = "[data-qa='skills-table'] [data-qa='resume-skill'], [data-qa='skills-table'] [title]:not([data-qa])"
SKILL_NAME = "[data-qa='resume-skill-name']"
SKILL_LEVEL = "[data-qa^='skill-level-title-']"
EDUCATION_BLOCK = "[data-qa='resume-education-block']"
EDUCATION = "[data-qa='resume-education-block'] [data-qa='resume-education-item'], [data-qa='resume-education-block'] [data-qa='cell']"
EDUCATION_INSTITUTION = "[data-qa='resume-education-institution'], [data-qa='cell-left-side'] div[class*='magritte-text_style-primary']"
EDUCATION_FACULTY = "[data-qa='resume-education-faculty']"
EDUCATION_SPECIALTY = "[data-qa='resume-education-specialty']"
EDUCATION_YEAR = "[data-qa='resume-education-year']"
EDUCATION_DEGREE = "[data-qa='resume-education-degree']"
LANGUAGE_BLOCK = "[data-qa='resume-languages-block']"
LANGUAGE = "[data-qa='resume-languages-block'] [data-qa='resume-language-item'], [data-qa='resume-languages-block'] [data-qa='resume-block-language-item']"
LANGUAGE_NAME = "[data-qa='resume-language-name']"
LANGUAGE_LEVEL = "[data-qa='resume-language-level']"
LANGUAGE_NATIVE_GROUP = "xpath=ancestor::div[contains(@class, 'magritte-v-spacing-container')][1]"
LANGUAGE_NATIVE_MARKER = "Родной"
COURSE = "[data-qa='resume-education-courses-block'] [data-qa='resume-course-item']"
COURSE_NAME = "[data-qa='resume-course-name'], [data-qa='resume-course-title']"
COURSE_BLOCK = "[data-qa='resume-education-courses-block']"
COURSE_CELL = "[data-qa='resume-education-courses-block'] [data-qa='cell']"
COURSE_TITLE = "[data-qa='cell-left-side'] div[class*='magritte-text_style-primary']"
COURSE_META = "[data-qa='cell-left-side'] div[class*='magritte-text_style-secondary']"
CERTIFICATION = "[data-qa='resume-certification-item']"
CERTIFICATION_NAME = "[data-qa='resume-certification-name'], [data-qa='resume-certification-title']"
AWARD = "[data-qa='resume-award-item']"
AWARD_NAME = "[data-qa='resume-award-name'], [data-qa='resume-award-title']"
PORTFOLIO = "[data-qa='resume-portfolio-item']"
PORTFOLIO_TITLE = "[data-qa='resume-portfolio-title'], [data-qa='resume-portfolio-name']"
ADDITIONAL_BLOCK = "[data-qa='resume-additional-info-block']"
ADDITIONAL = "[data-qa='resume-additional-section'], [data-qa='resume-additional-info-block'] [data-qa^='resume-additional-info-']"
UPDATED = "[data-qa='resume-update-date'], time[datetime]"
JOB_SEARCH_STATUS = "[data-qa='job-search-status']"
SOURCE_BADGES = "[data-qa='response-tag-achievements'] [data-qa='resume-card-tag-achievements'], [data-qa='response-tag-achievements']"
ACCOUNT_RESUME_LINKS = "a[href*='/resume/']"
