"""Zarplata.ru resume hooks; deliberately separate from HH hooks."""

NAME = "[data-qa='resume-personal-name']"
GENDER = "[data-qa='resume-gender']"
AGE = "[data-qa='resume-personal-age'], [data-qa='resume-personal-birthday']"
PHOTO = "[data-qa='resume-photo'], [data-qa='resume-block-photo'] img"
PHONE = "[data-qa='resume-contacts-phone'], a[href^='tel:']"
EMAIL = "[data-qa='resume-contact-email'], a[href^='mailto:']"
MESSENGER = "[data-qa='resume-contact-messenger'], [data-qa='resume-messenger']"
LINK = "[data-qa='resume-contact-link'], [data-qa='resume-portfolio'] a[href]"
TITLE = "[data-qa='resume-block-title-position'], [data-qa='resume-block-position']"
SPECIALIZATION = "[data-qa='resume-block-position-specialization'], [data-qa='resume-block-specialization-category']"
GRADE = "[data-qa='resume-grade']"
SALARY = "[data-qa='resume-salary']"
EMPLOYMENT = "[data-qa='resume-employment'], [data-qa='resume-employment-type']"
WORK_FORMAT = "[data-qa='resume-work-format'], [data-qa='resume-schedule']"
CITY = "[data-qa='resume-personal-address'], [data-qa='resume-address'], [data-qa='resume-location']"
RELOCATION = "[data-qa='relocation_relocation_possible'], [data-qa='resume-relocation']"
TRIPS = "[data-qa='resume-business-trips']"
CITIZENSHIP = "[data-qa='resume-citizenship']"
WORK_PERMIT = "[data-qa='resume-work-permit']"
ABOUT = "[data-qa='resume-about'], [data-qa='resume-block-about']"
EXPERIENCE = (
    "[data-qa='resume-block-experience'] [data-qa='resume-experience-item'], "
    "[data-qa='resume-block-experience'] > *, "
    "[data-qa='resume-list-card-experience'] [data-qa='profile-experience-company-card'], "
    "[data-qa='profile-experience-company-card']"
)
OWNER_EXPERIENCE_CARD = "[data-qa='profile-experience-company-card']"
EXPERIENCE_COMPANY = "[data-qa='resume-experience-company'], [data-qa='bloko-header-2'], .resume-block__title-text-wrapper"
EXPERIENCE_TITLE = "[data-qa='resume-experience-position'], [data-qa='resume-block-experience-position']"
EXPERIENCE_PERIOD = "[data-qa='resume-experience-period'], [data-qa='resume-block-experience-period'], .bloko-text_tertiary"
EXPERIENCE_DESCRIPTION = "[data-qa='resume-experience-description'], [data-qa='resume-block-experience-description']"
PROJECT = "[data-qa='resume-project-item']"
SKILL = (
    "[data-qa='resume-skill'], [data-qa='resume-block-skills'] li, "
    "[data-qa='skills-table'] [data-qa='bloko-tag__text'], "
    "[data-qa='skills-card'] [data-qa^='skill-tag-'], [data-qa^='skill-tag-']"
)
EDUCATION = (
    "[data-qa='resume-block-education-item'], "
    "[data-qa='resume-block-education'] [data-qa='resume-block-education-item'], "
    "[data-qa^='resume-list-card-education-item-']"
)
LANGUAGE = (
    "[data-qa='resume-block-language-item'], "
    "[data-qa='resume-block-languages'] [data-qa='resume-block-language-item'], "
    "[data-qa^='resume-list-card-language-item-']"
)
COURSE = "[data-qa='resume-course-item']"
CERTIFICATION = "[data-qa='resume-certification-item']"
AWARD = "[data-qa='resume-award-item']"
PORTFOLIO = "[data-qa='resume-portfolio-item']"
ADDITIONAL = "[data-qa='resume-block-additional'] [data-qa='resume-additional-section'], [data-qa='resume-additional-section']"
UPDATED = "time[datetime], [data-qa='resume-updated-at']"
ACCOUNT_RESUME_LINKS = "a[href*='/resume/']"
