import cssSource from './styles.css?raw'

const css = cssSource.replace(/\s+/gu, '')

test('desktop shell is full width with centered top navigation and main content', () => {
  expect(css).toContain('.shell{min-height:100vh;width:100%;}')
  expect(css).toContain('.topbar{position:sticky;top:0;width:100%;')
  expect(css).toContain('.topbar-inner{width:100%;max-width:1280px;')
  expect(css).toContain('.page{width:100%;max-width:1280px;margin:auto;')
  expect(css).toContain('.shell,main,.stats,.grid2,.cards,.panel,.statsarticle{min-width:0;max-width:100%;}')
  expect(css).not.toContain('.shell,main,.page,.stats,.grid2,.cards,.panel,.statsarticle{')
  expect(css).toContain('main{width:100%;min-width:0;}')
  expect(css).toContain('.topbar-actions>a,.button-link{display:inline-flex;')
  expect(css).toContain('.topbar-nav{display:flex;align-items:center;gap:4px;min-width:0;overflow-x:auto;')
  expect(css).not.toContain('.privacy-summary')
  expect(css).not.toContain('.model-status')
  expect(css).not.toContain('.dot')
  expect(css).not.toContain('header>div{')
  expect(css).not.toContain('headera,')
  expect(css).not.toContain('header{')
  expect(css).not.toContain('grid-template-columns:244pxminmax(0,1fr)')
  expect(css).not.toContain('.sidebar{')
})

test('session PDF report uses a compact branded action link', () => {
  expect(css).toContain('.session-actions{justify-content:flex-end;align-items:center;}')
  expect(css).toContain('.session-report-button{')
  expect(css).toContain('.session-report-icon{width:18px;height:18px;')
})

test('mobile breakpoint places horizontal top navigation on a second row', () => {
  expect(css).toContain('@media(max-width:900px){.topbar-inner{grid-template-columns:1frauto;grid-template-rows:autoauto;')
  expect(css).toContain('.topbar-nav{grid-column:1/-1;grid-row:2;overflow-x:auto;')
})

test('form width tokens and utilities define bounded, mobile-safe rails', () => {
  expect(css).toContain('--form-content-max:880px;')
  expect(css).toContain('--field-compact:320px;')
  expect(css).toContain('--field-medium:480px;')
  expect(css).toContain('--field-wide:720px;')
  expect(css).toContain('--field-prose:760px;')
  expect(css).toContain('.form-rail,.field-compact,.field-medium,.field-wide,.field-prose{width:100%;}')
  expect(css).toContain('.form-rail,.form-row{max-width:var(--form-content-max);}')
  expect(css).toContain('.form-row{width:100%;justify-content:start;}')
  expect(css).toContain('@media(max-width:600px){.topbar{min-height:60px;}')
  expect(css).toContain('.field-compact,.field-medium,.field-wide,.field-prose{max-width:none;}')
})

test('all page content shares the centered influence rail without shrinking panel content twice', () => {
  const rail = '.page>*{width:100%;max-width:calc(var(--form-content-max)+42px);margin-inline:auto;}'
  const safeguard = '.shell,main,.stats,.grid2,.cards,.panel,.statsarticle{min-width:0;max-width:100%;}'
  expect(css).toContain(rail)
  expect(css.indexOf(rail)).toBeGreaterThan(css.indexOf(safeguard))
  expect(css).not.toContain('.session-page>')
})

test('vacancy filters preserve the centered page rail', () => {
  expect(css).toContain('.vacancy-filters{display:grid;gap:1rem;margin-block:1rem;margin-inline:auto;')
})

test('resume editor fields and repeated experience cards have explicit boundaries', () => {
  expect(css).toContain('.resume-editor.form-contentinput:not([type="checkbox"]),.resume-editor.form-contentselect,.resume-editor.form-contenttextarea{')
  expect(css).toContain('.experience-card{border:1pxsolidvar(--line);background:var(--paper);border-radius:var(--radius-subcard);box-shadow:none;}')
  expect(css).toContain('.experience-card>.repeat-row{padding-bottom:10px;border-bottom:1pxsolidvar(--line);}')
})

test('multi-select uses aligned bordered rows and a full-width confirmation action', () => {
  expect(css).toContain('.multi-select-trigger{display:flex;align-items:center;justify-content:space-between;')
  expect(css).toContain('.multi-select-chevron.is-open{transform:rotate(180deg);}')
  expect(css).toContain('.multi-select-popover{display:grid;gap:10px;padding:12px;border:1pxsolidvar(--line);')
  expect(css).toContain('label.multi-select-option,.multi-select-option{display:flex;align-items:center;gap:12px;')
  expect(css).toContain('label.multi-select-option.is-selected,.multi-select-option.is-selected{border-color:var(--ink);background:var(--surface);}')
  expect(css).not.toContain('.formlabel.multi-select-option{')
  expect(css).toContain('.multi-select-confirm{width:100%;}')
})

test('all checkboxes share the resume control size and centered wrapper alignment', () => {
  expect(css).toContain('input[type="checkbox"]{box-sizing:border-box;flex:0018px;width:18px;height:18px;margin:0;padding:0;accent-color:var(--ink);cursor:pointer;}')
  expect(css).toContain('input[type="checkbox"]:disabled{cursor:not-allowed;}')
  expect(css).toContain('.checkline,.formlabel.checkline{display:flex;align-items:center;gap:8px;')
  expect(css).toContain('.selection-control{display:flex;align-items:center;gap:8px;')
})

test('profile layout keeps explicit equal and removable rails', () => {
  expect(css).toContain('.profile-pair-row,.profile-pair-remove-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));')
  expect(css).toContain('.profile-remove-row{display:grid;grid-template-columns:minmax(0,1fr)auto;')
  expect(css).toContain('.profile-pair-remove-row{grid-template-columns:repeat(2,minmax(0,1fr))auto;}')
  expect(css).toContain('.profile-pair-row,.profile-pair-remove-row{grid-template-columns:minmax(0,1fr);}')
  expect(css).toContain('.profile-pair-remove-row>:nth-child(1),.profile-pair-remove-row>:nth-child(2){grid-column:1;}')
  expect(css).toContain('.profile-pair-remove-row>.icon-button{grid-column:2;grid-row:1/3;')
})

test('notification items remain readable and opaque despite global button styles', () => {
  expect(css).toContain('.notification-item{display:grid;gap:4px;width:100%;min-height:auto;border:0;border-bottom:1pxsolidvar(--line);')
  expect(css).toContain('.notification-item:focus-visible{opacity:1;}')
  expect(css).toContain('.notification-itemstrong,.notification-itemspan{color:var(--ink);font-size:13px;line-height:1.35;}')
  expect(css).toContain('.notification-item.unread{background:var(--surface);}')
})

test('influence tooltips use a layered DOM tooltip with an italic footnote', () => {
  expect(css).toContain('.influence-control:focus-within{z-index:3;}')
  expect(css).toContain('.tooltip{position:absolute;z-index:4;')
  expect(css).toContain('width:min(360px,calc(100vw-48px));')
  expect(css).toContain('.tooltip-wrap:focus-within.tooltip{opacity:1;transform:translateY(0);}')
  expect(css).toContain('.tooltipem{display:block;margin-top:7px;font-style:italic;}')
  expect(css).toContain('.question-button:hover{opacity:1;}')
  expect(css).not.toContain('.question-button::after')
})

test('influence labels share the range axis at each slider stop', () => {
  expect(css).toContain('.influence-axis{position:relative;padding-inline:clamp(42px,5vw,52px);}')
  expect(css).toContain('.forminput.influence-range{display:block;width:100%;height:18px;margin:0;padding:0;border:0;')
  expect(css).toContain('appearance:none;')
  expect(css).toContain('.influence-levels{position:relative;height:18px;margin:7px9px0;')
  expect(css).not.toContain('inset:25px0auto')
  expect(css).toContain('left:var(--level-position);transform:translateX(-50%);')
  expect(css).not.toContain('grid-template-columns:repeat(3,1fr)')
})

test('motion contracts expose shared tokens, reduced motion, and anchored overlays', () => {
  expect(css).toContain('--accent:#0a0a0a;')
  expect(css).toContain('--ease-out:cubic-bezier(.23,1,.32,1);')
  expect(css).toContain('--ease-in-out:cubic-bezier(.77,0,.175,1);')
  expect(css).toContain('--ease-drawer:cubic-bezier(.32,.72,0,1);')
  expect(css).toContain('--duration-fast:120ms;')
  expect(css).toContain('--duration-ui:180ms;')
  expect(css).toContain('.notification-popover[data-starting-style],.notification-popover[data-ending-style]')
  expect(css).toContain('.multi-select-positioner{z-index:var(--z-popover);')
  expect(css).toContain('.vacancy-disclosuresummary{display:grid;grid-template-columns:minmax(0,1fr)90pxauto40px;}')
  expect(css).toContain('.vacancy-disclosure-control{display:inline-grid;width:38px;height:38px;place-items:center;border:1pxsolidvar(--line);border-radius:50%;')
  expect(css).toContain('.vacancy-chevron{display:block;width:18px;height:18px;transition:transform140msvar(--ease-out);}')
  expect(css).not.toContain('.vacancy-disclosure.vacancy-disclosure-close{')
  expect(css).not.toContain('.vacancy-disclosure[open].vacancy-disclosure-open{')
  expect(css).toContain('.vacancy-disclosure[open].vacancy-chevron,.vacancy-disclosuresummary[aria-expanded="true"].vacancy-chevron')
  expect(css).toContain('.animated-repeat-item{opacity:1;transform:translateY(0);transition:opacityvar(--duration-ui)var(--ease-out),transformvar(--duration-ui)var(--ease-out);}')
  expect(css).toContain('@starting-style{.animated-repeat-item{opacity:0;transform:translateY(6px);}}')
  expect(css).not.toContain('@keyframesrepeat-item-in')
  expect(css).toContain('.notification-positioner{z-index:var(--z-popover);')
  expect(css).toContain('.topbar-nav-icon{display:none;}')
  expect(css).toContain('.topbar-nav-icon{display:block;width:18px;height:18px;}')
  expect(css).toContain('.vacancy-disclosuresummary{grid-template-columns:minmax(0,1fr)40px;grid-template-rows:autoautoauto;gap:10px;padding:16px;}')
  expect(css).toContain('.vacancy-disclosuresummary>.vacancy-main{grid-column:1/-1;grid-row:1;}')
  expect(css).toContain('.vacancy-disclosuresummary>.status{grid-column:1/-1;grid-row:2;')
  expect(css).toContain('.vacancy-disclosuresummary>.score-total{grid-column:1;grid-row:3;')
  expect(css).toContain('.vacancy-disclosuresummary>.vacancy-disclosure-control{grid-column:2;grid-row:3;')
  expect(css).toContain('.vacancy-disclosure.score-total{justify-content:flex-end;gap:2px;white-space:nowrap;}')
  expect(css).toContain('@media(prefers-reduced-motion:reduce)')
  expect(css).not.toContain('*,*::before,*::after{animation-duration:1ms;')
  expect(css).toContain('.topbar-nav{position:fixed;z-index:var(--z-topbar);right:0;bottom:0;left:0;')
})

test('model settings fields use the shared platform field treatment', () => {
  expect(css).toContain('.model-settingsinput,.model-settingsselect{width:100%;box-sizing:border-box;min-height:var(--field-height);border:1pxsolidtransparent;border-radius:var(--radius-control);')
  expect(css).toContain('.model-settingsinput::placeholder{color:var(--muted);opacity:1;}')
  expect(css).toContain('.model-settingsinput:focus,.model-settingsselect:focus{border-color:var(--ink);background:var(--paper);box-shadow:var(--focus-ring);}')
})

test('profile save bar is compact on desktop and clears the bottom nav on mobile', () => {
  expect(css).toContain('.profile-save-bar{width:fit-content;max-width:100%;margin-left:auto;padding:8px;border-radius:18px;}')
  expect(css).toContain('.profile-save-bar{width:fit-content;margin-left:auto;bottom:calc(76px+env(safe-area-inset-bottom));}')
  expect(css).not.toContain('.profile-save-bar>button{width:100%;}')
})

test('single select and experience duties match platform field contracts', () => {
  expect(css).toContain('.single-select{position:relative;display:grid;gap:8px;width:100%;}')
  expect(css).toContain('.single-select-label{font-size:14px;font-weight:500;color:var(--soft);}')
  expect(css).toContain('.single-select-trigger{display:flex;align-items:center;justify-content:space-between;gap:12px;width:100%;min-height:var(--field-height);')
  expect(css).toContain('.session-top-row{align-items:start;}')
  expect(css).toContain('.single-select-value{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}')
  expect(css).toContain('.single-select-positioner{z-index:var(--z-popover);width:min(var(--anchor-width,100%),calc(100vw-24px));')
  expect(css).toContain('.single-select-popup{width:100%;max-height:min(var(--available-height,360px),calc(100vh-32px));overflow:auto;padding:12px;border:1pxsolidvar(--line);border-radius:var(--radius-popover);')
  expect(css).toContain('.single-select-list{display:grid;gap:8px;}')
  expect(css).toContain('.single-select-option{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:var(--field-height);padding:10px12px;border:1pxsolidvar(--line);border-radius:var(--radius-control);')
  expect(css).toContain('.single-select-option[data-highlighted],.single-select-option[data-selected]{border-color:var(--ink);background:var(--surface);}')
  expect(css).toContain('.single-select-option:focus-visible{box-shadow:none!important;}')
  expect(css).toContain('.single-select-indicator{flex:00auto;color:var(--ink);}')
  expect(css).not.toContain('.single-select-check{')
  expect(css).toContain('.single-select-popup[data-starting-style],.single-select-popup[data-ending-style]{opacity:0;transform:translateY(-4px)scale(.98);}')
  expect(css).toContain('.resume-editor.form-contenttextarea.experience-duties{min-height:160px;padding:14px16px;font-size:14px;')
  expect(css).toContain('.resume-editor.form-contenttextarea.experience-duties:hover{')
  expect(css).toContain('.resume-editor.form-contenttextarea.experience-duties:focus{border-color:var(--ink);background:var(--paper);}')
  expect(css).toContain('.single-select-popup{transition:opacity120mslinear!important;transform:none!important;}')
})

test('sonner close control is integrated into the toast', () => {
  expect(css).toContain('[data-sonner-toast]:has([data-close-button]){padding-right:52px!important;}')
  expect(css).toContain('[data-sonner-toast][data-close-button]{position:absolute!important;left:auto!important;right:10px!important;top:50%!important;transform:translateY(-50%)!important;')
  expect(css).toContain('min-width:32px!important;min-height:32px!important;width:32px!important;height:32px!important;padding:0!important;border:0!important;border-radius:10px!important;background:transparent!important;color:currentColor!important;box-shadow:none!important;opacity:.58;}')
  expect(css).toContain('[data-sonner-toast][data-close-button]:hover{background:color-mix(insrgb,currentColor10%,transparent)!important;opacity:1;}')
  expect(css).toContain('[data-sonner-toast][data-close-button]:focus-visible{opacity:1;box-shadow:0002pxvar(--paper),0004pxcurrentColor!important;}')
  expect(css).toContain('[data-sonner-toast][data-close-button]svg{width:16px!important;height:16px!important;}')
  expect(css).not.toContain('[data-close-button]{left:-')
})

test('overview status strip reserves the first block for model readiness', () => {
  expect(css).toContain('.overview-status-strip')
  expect(css).toContain('grid-template-columns:repeat(4,minmax(0,1fr))')
  expect(css).not.toContain('.preview-model-link')
  expect(css).not.toContain('--surface-2')
  expect(css).not.toContain('--text-muted')
})

test('overview keeps hero styles while removing retired lower sections', () => {
  expect(css).toContain('.overview-page{width:100%;max-width:none;')
  expect(css).toContain('.overview-hero-section{background:#f5f5f5;}')
  expect(css).toContain('.overview-container{width:100%;max-width:1280px;')
  expect(css).toContain('.overview-hero{display:grid;')
  expect(css).toContain('.overview-eyebrow{display:inline-flex;')
  expect(css).toContain('.overview-actions{display:flex;')
  expect(css).not.toContain('.overview-how')
  expect(css).not.toContain('.overview-routes')
  expect(css).not.toContain('.overview-control')
  expect(css).not.toContain('.overview-final')
  expect(css).not.toContain('.overview-footer')
  expect(css).not.toContain('.overview-steps')
  expect(css).not.toContain('.overview-route-grid')
  expect(css).not.toContain('.overview-section-label')
})

test('vacancy disclosure keeps desktop, tablet, and mobile layout contracts', () => {
  expect(css).toContain('.vacancy-disclosuresummary{grid-template-columns:minmax(0,1fr)104px150px40px;}')
  expect(css).toContain('.vacancy-disclosuresummary{grid-template-columns:minmax(0,1fr)96px150px40px;}')
  expect(css).toContain('.vacancy-disclosure.vacancy-mainb{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;line-clamp:2;}')
  expect(css.match(/-webkit-line-clamp:2;/gu)).toHaveLength(1)
  expect(css).toContain('.vacancy-disclosuresummary>.status{justify-self:end;')
  expect(css).toContain('font-variant-numeric:tabular-nums;')
  expect(css).toContain('@media(max-width:600px)')
})

test('design system exposes unified control, field, focus, tone, and layering contracts', () => {
  expect(css).toContain('--radius-card:24px;')
  expect(css).toContain('--radius-control:18px;')
  expect(css).toContain('--field-height:48px;')
  expect(css).toContain('--control-height:44px;')
  expect(css).toContain('--focus-ring:0003pxvar(--paper),0005pxvar(--ink);')
  expect(css).toContain('.icon-button{width:40px;min-width:40px;height:40px;min-height:40px;display:inline-grid;place-items:center;')
  expect(css).toContain('.notice-success{')
  expect(css).toContain('.notice-danger,.notice.error{')
  expect(css).toContain('.notice-warning{')
  expect(css).toContain('.notice-info{')
  expect(css).toContain('@media(hover:hover)and(pointer:fine)')
  expect(css).not.toContain('button:hover,.button-link:hover')
  expect(css).toContain('@media(prefers-contrast:more)')
  expect(css).toContain('@media(prefers-reduced-transparency:reduce)')
})
